const CACHE='epaule-v6-cache-migration-1';
const VERSION='v6-cache-migration-1';
const SHELL=['./','./index.html',`./styles-v4.css?${VERSION}`,`./app-v4.bundle.js?${VERSION}`,`./pwa.js?${VERSION}`,`./manifest.webmanifest?${VERSION}`,'./icons/icon.svg','./icons/icon-192.png','./icons/icon-512.png'];
const isCritical=request=>request.mode==='navigate'||['script','style','worker','manifest'].includes(request.destination)||/\.(?:html|js|css|gltf|bin|webmanifest)$/i.test(new URL(request.url).pathname);
async function networkFirst(request){const cache=await caches.open(CACHE);try{const response=await fetch(request,{cache:'no-store'});if(response.ok)await cache.put(request,response.clone());return response}catch(error){const cached=await caches.match(request);if(cached)return cached;if(request.mode==='navigate')return caches.match('./index.html');throw error}}
async function cacheFirst(request){const cached=await caches.match(request);if(cached)return cached;const response=await fetch(request);if(response.ok){const cache=await caches.open(CACHE);await cache.put(request,response.clone())}return response}
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(SHELL)));self.skipWaiting()});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();const old=keys.filter(key=>key!==CACHE);await Promise.all(old.map(key=>caches.delete(key)));await self.clients.claim();if(old.length){const windows=await self.clients.matchAll({type:'window',includeUncontrolled:true});await Promise.all(windows.map(client=>client.navigate(client.url).catch(()=>null)))}})())});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==self.location.origin)return;event.respondWith(isCritical(event.request)?networkFirst(event.request):cacheFirst(event.request))});
