import * as THREE from 'three';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';

const EX=[
{id:'clap',title:'Pompes dynamiques à genoux',cat:'Activation en charge',summary:'Descente contrôlée, poussée vive, bref allègement des mains puis réception souple.',steps:['Aligner le tronc des genoux aux épaules.','Descendre en fléchissant les coudes.','Repousser rapidement sans perdre le contrôle.','Réceptionner avec les coudes souples.'],cues:['Épaules loin des oreilles.','Bassin stable.','Aucun effondrement de l’épaule gauche.'],dose:[3,6,'Poids du corps'],muscles:[['Triceps',3],['Pectoral',3],['Dentelé',2],['Coiffe',1]]},
{id:'shift',title:'Balanciers droite–gauche',cat:'Stabilité en appui',summary:'Transférer progressivement le poids d’une main vers l’autre sans tourner le bassin.',steps:['Prendre la position de pompe à genoux.','Déplacer le thorax vers la droite.','Revenir au centre.','Transférer vers la gauche.'],cues:['Mains fixes.','Mouvement lent.','Tronc et bassin solidaires.'],dose:[3,10,'Poids du corps'],muscles:[['Coiffe',3],['Dentelé',3],['Trapèze',2],['Tronc',2]]},
{id:'supine',title:'Rotations allongées en 90/90',cat:'Coiffe des rotateurs',summary:'Bras ouverts et coudes fléchis, descendre les avant-bras avec retenue puis remonter sans déplacer les coudes.',steps:['S’allonger, bras ouverts à 90°.','Garder les coudes fléchis à 90°.','Descendre lentement les avant-bras.','Remonter de façon vive mais contrôlée.'],cues:['Côtes stables.','Coudes fixes.','Ne pas forcer la fin d’amplitude.'],dose:[3,12,'1,5 kg / main'],muscles:[['Infra-épineux',3],['Coiffe',3],['Petit rond',2],['Omoplate',1]]},
{id:'dive',title:'Pompe plongeante arrière–avant',cat:'Amplitude en charge',summary:'Reculer, passer le menton près du sol, avancer les épaules au-delà des mains, remonter puis revenir.',steps:['Épaules en retrait des mains.','Descendre le menton au ras du sol.','Glisser vers l’avant, épaules au-delà des mains.','Tendre les bras et remonter.','Revenir à quatre pattes.'],cues:['Trajectoire fluide.','Menton rentré.','Mains et genoux restent en appui.'],dose:[3,8,'Poids du corps'],muscles:[['Triceps',3],['Dentelé',3],['Pectoral',2],['Coiffe',2]]},
{id:'row',title:'Tirage puis extension du triceps',cat:'Dos et bras',summary:'À quatre pattes, remonter le coude gauche puis tendre l’avant-bras vers l’arrière.',steps:['Stabiliser l’appui droit et les genoux.','Tirer le coude gauche près du tronc.','Maintenir le bras.','Tendre le coude vers l’arrière.','Revenir lentement.'],cues:['Dos neutre.','Pas de rotation du bassin.','Pas d’élan.'],dose:[3,10,'1,5 kg gauche'],muscles:[['Triceps',3],['Rhomboïdes',3],['Trapèze moyen',2],['Deltoïde postérieur',2]]},
{id:'rotate',title:'Rotation externe bras relevé',cat:'Rotation et contrôle',summary:'Bras gauche à hauteur d’épaule, coude fléchi : relever l’avant-bras puis redescendre avec retenue.',steps:['Stabiliser la position quadrupédique.','Élever le coude gauche sur le côté.','Faire pivoter l’avant-bras vers le haut.','Redescendre lentement.'],cues:['Humérus stable.','Épaule loin de l’oreille.','Thorax peu mobile.'],dose:[3,10,'1,5 kg gauche'],muscles:[['Infra-épineux',3],['Petit rond',3],['Coiffe',2],['Trapèze inférieur',1]]},
{id:'reach',title:'Projection du bras vers l’avant',cat:'Coordination scapulo-humérale',summary:'Depuis quatre pattes, allonger le bras gauche dans le prolongement du corps puis revenir sous l’épaule.',steps:['Menton rentré et dos neutre.','Décoller la main gauche.','Allonger le bras près de la tête.','Revenir lentement.'],cues:['Bassin parallèle au sol.','Pas de haussement d’épaule.','Trajectoire continue.'],dose:[3,10,'Selon consigne'],muscles:[['Dentelé',3],['Deltoïde antérieur',2],['Trapèze inférieur',2],['Coiffe',2]]}
];
const $=s=>document.querySelector(s), ui={list:$('#exerciseList'),title:$('#title'),num:$('#num'),cat:$('#category'),summary:$('#summary'),steps:$('#steps'),cues:$('#cues'),chips:$('#chips'),sets:$('#sets'),reps:$('#reps'),load:$('#load'),play:$('#play'),speed:$('#speed'),timeline:$('#timeline'),phase:$('#phase'),time:$('#time'),muscles:$('#muscles'),sequence:$('#sequence')};
let current=0,t=0,playing=true,auto=false,showMuscles=true,ready=false,last=performance.now();
function renderInfo(){const e=EX[current];ui.list.innerHTML=EX.map((x,n)=>`<button class="exercise ${n===current?'active':''}" data-n="${n}"><span class="n">${String(n+1).padStart(2,'0')}</span><span><strong>${x.title}</strong><small>${x.cat}</small></span></button>`).join('');ui.list.querySelectorAll('button').forEach(b=>b.onclick=()=>{current=+b.dataset.n;t=0;renderInfo()});ui.num.textContent=String(current+1).padStart(2,'0');ui.title.textContent=e.title;ui.cat.textContent=e.cat;ui.summary.textContent=e.summary;ui.steps.innerHTML=e.steps.map(x=>`<li>${x}</li>`).join('');ui.cues.innerHTML=e.cues.map(x=>`<li>${x}</li>`).join('');ui.chips.innerHTML=e.muscles.map(x=>`<span class="chip ${x[1]===3?'p':x[1]===2?'s':'t'}">${x[0]}</span>`).join('');[ui.sets.value,ui.reps.value,ui.load.value]=e.dose}renderInfo();

const host=$('#viewer'),scene=new THREE.Scene();scene.background=new THREE.Color(0xcadbd7);scene.fog=new THREE.Fog(0xcadbd7,6,11);
const camera=new THREE.PerspectiveCamera(38,1,.01,30);camera.position.set(5.0,2.4,.5);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;host.prepend(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.62,.25);controls.enableDamping=true;controls.minDistance=2.2;controls.maxDistance=7;
scene.add(new THREE.HemisphereLight(0xf5fffd,0x36514c,2.3));const key=new THREE.DirectionalLight(0xffffff,3.2);key.position.set(3,5,2);key.castShadow=true;scene.add(key);const rim=new THREE.DirectionalLight(0x9eeadd,1.8);rim.position.set(-3,2,-3);scene.add(rim);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(12,12),new THREE.MeshStandardMaterial({color:0x9eb5b0,roughness:.92}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
const pivot=new THREE.Group();scene.add(pivot);let model,bones={},rest=new Map(),baseScale=1;
const overlayGroup=new THREE.Group();scene.add(overlayGroup);const overlay={};[['shoulder',0xe93c2d,.16],['arm',0xe93c2d,.13],['chest',0xf18a34,.15],['scapula',0xf2c54e,.14]].forEach(([n,c,r])=>{const m=new THREE.Mesh(new THREE.SphereGeometry(r,28,18),new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:.48,depthWrite:false,blending:THREE.AdditiveBlending}));overlay[n]=m;overlayGroup.add(m)});
const V=(x,y,z)=>new THREE.Vector3(x,y,z),q0=new THREE.Quaternion(),q1=new THREE.Quaternion(),q2=new THREE.Quaternion(),v0=new THREE.Vector3(),v1=new THREE.Vector3();
function wp(name){return bones[name].getWorldPosition(new THREE.Vector3())}
function resetPose(){if(!model)return;for(const [n,r] of rest){const b=bones[n];b.position.copy(r.p);b.quaternion.copy(r.q);b.scale.copy(r.s)}pivot.position.set(0,0,0);pivot.rotation.set(0,0,0);pivot.scale.setScalar(1);model.updateMatrixWorld(true)}
function aim(name,child,target){const b=bones[name],c=bones[child];if(!b||!c)return;b.updateWorldMatrix(true,false);c.updateWorldMatrix(true,false);const bp=b.getWorldPosition(v0),cp=c.getWorldPosition(v1);const from=cp.clone().sub(bp).normalize(),to=target.clone().sub(bp).normalize();if(from.lengthSq()<.5||to.lengthSq()<.5)return;const delta=q0.setFromUnitVectors(from,to);const world=b.getWorldQuaternion(q1);const parent=b.parent.getWorldQuaternion(q2).invert();b.quaternion.copy(parent.multiply(delta.multiply(world)));b.updateWorldMatrix(true,true)}
function support({y=.72,z=0,x=0,bend=.08,left=null,knees=true}){resetPose();pivot.rotation.x=Math.PI/2;pivot.position.set(x,y,z);model.updateMatrixWorld(true);const sl=wp('upperarm_l'),sr=wp('upperarm_r'),hl=wp('thigh_l'),hr=wp('thigh_r');const handL=V(.27,.035,1.43),handR=V(-.27,.035,1.43);const elbowL=sl.clone().lerp(handL,.52).add(V(.16*bend,.05,0)),elbowR=sr.clone().lerp(handR,.52).add(V(-.16*bend,.05,0));if(left){aim('upperarm_l','lowerarm_l',left.elbow);aim('lowerarm_l','hand_l',left.wrist)}else{aim('upperarm_l','lowerarm_l',elbowL);aim('lowerarm_l','hand_l',handL)}aim('upperarm_r','lowerarm_r',elbowR);aim('lowerarm_r','hand_r',handR);if(knees){const kl=V(hl.x,.055,.48),kr=V(hr.x,.055,.48),fl=V(hl.x,.08,.02),fr=V(hr.x,.08,.02);aim('thigh_l','calf_l',kl);aim('calf_l','foot_l',fl);aim('thigh_r','calf_r',kr);aim('calf_r','foot_r',fr)}model.updateMatrixWorld(true)}
function supine(q){resetPose();pivot.rotation.x=-Math.PI/2;pivot.position.set(0,.18,-.1);model.updateMatrixWorld(true);for(const side of ['l','r']){const sg=side==='l'?1:-1,sh=wp('upperarm_'+side);const el=V(sg*.76,.25,sh.z),wr=V(sg*.76,.25+.5*(1-q),sh.z-.34*q);aim('upperarm_'+side,'lowerarm_'+side,el);aim('lowerarm_'+side,'hand_'+side,wr)}model.updateMatrixWorld(true)}
function pose(ex,u){const wave=(1-Math.cos(u*Math.PI*2))/2;if(ex.id==='clap'){const lift=Math.max(0,1-Math.abs(u-.5)*8);support({y:.73-.34*wave+.09*lift,bend:.55*wave})}else if(ex.id==='shift'){support({x:Math.sin(u*Math.PI*2)*.19,bend:.14})}else if(ex.id==='supine'){supine(wave)}else if(ex.id==='dive'){let y,z,b;if(u<.2){const a=u/.2;y=.78;z=-.32*(1-a);b=.12}else if(u<.46){const a=(u-.2)/.26;y=.78-.48*a;z=.02+.08*a;b=.8*a}else if(u<.67){const a=(u-.46)/.21;y=.30;z=.10+.53*a;b=.8}else if(u<.84){const a=(u-.67)/.17;y=.30+.48*a;z=.63;b=.8*(1-a)}else{const a=(u-.84)/.16;y=.78;z=.63-.95*a;b=.12}support({y,z,bend:b})}else if(ex.id==='row'){resetPose();pivot.rotation.x=Math.PI/2;pivot.position.set(0,.72,0);model.updateMatrixWorld(true);const sh=wp('upperarm_l'),sg=sh.x>0?1:-1;if(u<.52){const a=(1-Math.cos(u/.52*Math.PI))/2;support({left:{elbow:sh.clone().add(V(.26*sg,.18*a,-.12)),wrist:sh.clone().add(V(.12*sg,-.08+.22*a,-.20))},bend:.1})}else{const a=(1-Math.cos((u-.52)/.48*Math.PI))/2;support({left:{elbow:sh.clone().add(V(.26*sg,.18,-.12)),wrist:sh.clone().add(V(.12*sg,.11,-.20-.62*a))},bend:.1})}}else if(ex.id==='rotate'){resetPose();pivot.rotation.x=Math.PI/2;pivot.position.set(0,.72,0);model.updateMatrixWorld(true);const sh=wp('upperarm_l'),sg=sh.x>0?1:-1,el=sh.clone().add(V(.48*sg,.03,.02)),wr=el.clone().add(V(0,.08+.48*wave,.28*(1-wave)));support({left:{elbow:el,wrist:wr},bend:.1})}else if(ex.id==='reach'){resetPose();pivot.rotation.x=Math.PI/2;pivot.position.set(0,.72,0);model.updateMatrixWorld(true);const sh=wp('upperarm_l'),sg=sh.x>0?1:-1,el=sh.clone().add(V(.04*sg,.02,.38*wave)),wr=sh.clone().add(V(.05*sg,.04,.82*wave));support({left:{elbow:el,wrist:wr},bend:.08})}updateOverlays(ex)}
function updateOverlays(ex){if(!ready)return;overlayGroup.visible=showMuscles;const sh=wp('upperarm_l'),el=wp('lowerarm_l'),cl=wp('clavicle_l'),sp=wp('spine_03');overlay.shoulder.position.copy(sh);overlay.arm.position.copy(sh).lerp(el,.55);overlay.chest.position.copy(cl).add(V(-.06,-.06,.04));overlay.scapula.position.copy(sp).add(V(.16,.05,.05));const map={clap:[1,1,1,1],shift:[1,.65,.8,1],supine:[1,.8,.4,.8],dive:[1,1,1,1],row:[.75,1,.45,1],rotate:[1,.7,.35,.9],reach:[1,.45,.7,1]}[ex.id];Object.values(overlay).forEach((m,i)=>m.scale.setScalar(map[i]))}
new GLTFLoader().load('assets/quaternius/fullbody/Superhero_Male_FullBody.gltf',g=>{model=g.scene;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.frustumCulled=false}if(o.isBone)bones[o.name]=o});pivot.add(model);let box=new THREE.Box3().setFromObject(model),h=box.max.y-box.min.y;baseScale=2.0/h;model.scale.setScalar(baseScale);model.updateMatrixWorld(true);box.setFromObject(model);model.position.x-=((box.min.x+box.max.x)/2);model.position.y-=box.min.y;model.position.z-=((box.min.z+box.max.z)/2);model.updateMatrixWorld(true);for(const [n,b] of Object.entries(bones))rest.set(n,{p:b.position.clone(),q:b.quaternion.clone(),s:b.scale.clone()});ready=true;$('#loader').remove();document.documentElement.dataset.ready='true';pose(EX[current],t)},undefined,e=>{$('#loader').textContent='Échec du chargement du modèle';console.error(e)});
function resize(){const r=host.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(host);resize();
ui.play.onclick=()=>{playing=!playing;ui.play.textContent=playing?'Pause':'Lecture'};ui.timeline.oninput=()=>{t=+ui.timeline.value/1000;playing=false;ui.play.textContent='Lecture'};ui.muscles.onclick=()=>{showMuscles=!showMuscles;ui.muscles.classList.toggle('active',showMuscles)};ui.sequence.onclick=()=>{auto=!auto;ui.sequence.textContent=auto?'Arrêter':'Tout lire'};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const v=b.dataset.view;if(v==='left')camera.position.set(3.8,2.1,-.5);if(v==='front')camera.position.set(0,2.4,-4);if(v==='back')camera.position.set(0,2.4,3.2);controls.target.set(0,.65,-.65)});$('#resetView').onclick=()=>{camera.position.set(5.0,2.4,.5);controls.target.set(0,.72,-.65)};
function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(playing){t+=dt*(+ui.speed.value||1)/5;if(t>=1){t%=1;if(auto){current=(current+1)%EX.length;renderInfo()}}ui.timeline.value=t*1000}if(ready)pose(EX[current],t);ui.phase.textContent=t<.12?'Position initiale':t<.42?'Mise en mouvement':t<.72?'Phase active':'Retour contrôlé';ui.time.textContent=(t*5).toFixed(1).replace('.',',')+' s';controls.update();renderer.render(scene,camera);requestAnimationFrame(loop)}requestAnimationFrame(loop);
